### ISSUE TITLE
提议支持 SQLite

### ISSUE THREAD

**Issue by solicomo** [imxz/LetsBBS#3]
现在的社区，规模很大的非常有限，而那些已经上了规模的社区一般会选择自主开发。

而很多非社区站点都会提供一个类似“论坛”的模块供用户反馈意见。

所以，小社区应该是更大的用户群。

而对于大部分小社区来说，SQLite 不但部署、迁移简单，性能也能胜任。

**Comment by imxz** [comment]
暂不考虑。谢谢你的建议。
